version: '3.8'

services:
  # Redis service for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # FastAPI backend service
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - ./webscraper:/app/webscraper
    restart: unless-stopped

  # Telegram bot service
  telegram-bot:
    build:
      context: .
      dockerfile: telegram-bot/Dockerfile
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_USERNAME=${BOT_USERNAME}
    depends_on:
      - api
    restart: unless-stopped

volumes:
  redis_data:
